// src/components/EditableItemRow.styles.ts

export const editableItemRowStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    borderRadius: '8px',
    border: '1px solid #E6E9EF',
    background: '#FFF',
    boxShadow: '0 0 16px 0 rgba(0, 0, 0, 0.08)',
    padding: '16px',
    marginBottom: 16,
  },
  fieldRow: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: 12,
  },
  label: {
    width: 80,
  },
  input: {
    flex: 1,
    border: 'none',
    outline: 'none',
    background: 'transparent',
    fontSize: '1rem',
    fontWeight: 500,
    color: '#1E0803',
    textAlign: 'right' as const,
  },
  categoryLabel: {
    width: 80,
    whiteSpace: 'nowrap' as const,
  },
  categorySelectWrapper: {
    flex: 1,
  },
  categorySelect: {
    width: '100%',
    whiteSpace: 'normal' as const,
    wordBreak: 'break-word' as const,
    textAlign: 'right' as const,
  },
  buttonCancel: {
    padding: '4px 0px',
    fontSize: '1.1rem',
    textAlign: 'left' as const,
    borderRadius: 6,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    marginTop: 12,
    color: '#F33F44',
    borderBottom: '1px solid transparent',
    transition: 'border-color 120ms ease',
  },
  buttonDelete: (isValid: boolean, isActive: boolean) => ({
    padding: '4px 0px',
    fontSize: '1.1rem',
    textAlign: 'left' as const,
    borderRadius: 6,
    border: 'none',
    background: 'transparent',
    cursor: isValid ? 'pointer' : 'not-allowed',
    marginTop: 12,
    color: isActive ? "#A61D24" : isValid ? "#F33F44" : "#aaa",
    borderBottom: '1px solid transparent',
    transition: 'border-color 120ms ease',
  }),
  buttonDone: (isValid: boolean, isActive: boolean) => ({
    marginLeft: 'auto',
    padding: '4px 0px',
    fontSize: '1.1rem',
    borderRadius: 6,
    border: 'none',
    background: 'transparent',
    cursor: isValid ? 'pointer' : 'not-allowed',
    marginTop: 12,
    color: isActive ? "#CC5200" : isValid ? "#FF6600" : "#aaa",
    borderBottom: '1px solid transparent',
    transition: 'border-color 120ms ease',
  }),
  confirmOverlay: {
    position: 'fixed' as const,
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 999,
  },
  confirmBox: {
    background: '#fff',
    padding: 16,
    borderRadius: 8,
    maxWidth: 400,
    textAlign: 'center' as const,
    margin: 30,
  },
  confirmButtons: {
    display: 'flex',
    justifyContent: 'center',
    gap: 16,
  },
  confirmCancelBtn: {
    padding: '6px 16px',
    border: 'none',
    borderRadius: 100,
  },
  confirmConfirmBtn: {
    padding: '6px 16px',
    background: '#EC6A38',
    color: '#fff',
    border: 'none',
    borderRadius: 100,
  },
  displayMode: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    background: '#fff',
    borderRadius: '8px',
    border: '1px solid #E6E9EF',
    marginBottom: 12,
    cursor: 'pointer',
  },
  displayLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  displayRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    whiteSpace: 'nowrap' as const,
  }
};
